### ISSUE TITLE
WLED Effects FPP page not complete

### ISSUE THREAD

**Issue by jeepinjason** [adamcoulombe/fpp-WledEffects#1]
Installed on FPP 5.5 and non of the effect buttons, model selector, or color selectors show up on the UI.  

![image](https://user-images.githubusercontent.com/75093302/180315092-9b2331c5-da16-4908-8b5b-b269c60710bf.png)

**Comment by adamcoulombe** [comment]
it seems the ui isnt being populated with any system data.

Would you care to post a console log from google chrome by pressing F12 and copying everything that shows up in the console when you load the page?

**Comment by jeepinjason** [comment]
OK so further investigation.  It works *better* when I'm logged in on my local network, but when logging in remotely thru Dataplicity is when the plugin is blank...  So it appears to be an issue with the Dataplicity passthrough.

But on the local, it still doesn't give me the model list, or the color selections.  

![image](https://user-images.githubusercontent.com/75093302/180590899-119cb884-75a6-4cbb-b0d9-becaf6b47458.png)

**Comment by jeepinjason** [comment]
Here's the Console log
![image](https://user-images.githubusercontent.com/75093302/180590956-44eef539-a085-4841-b74b-2c99fc5217c2.png)

**Comment by ravenridgelights-turtle** [comment]
I am experience  the same .. i would love for this to work but at the moment its not pulling in models , color picker , etc 
 but i love the idea of real buttons . i could see this being made into a app for us as well .

**Comment by ravenridgelights-turtle** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at HTMLButtonElement.<anonymous> (plugin.php?plugin=fpp-WledEffects&page=wledeffects.js&nopage=1:190:59)
    at Function.each (jquery-latest.min.js:2:2976)
    at S.fn.init.each (jquery-latest.min.js:2:1454)
    at Object.success (plugin.php?plugin=fpp-WledEffects&page=wledeffects.js&nopage=1:185:57)
    at c (jquery-latest.min.js:2:28294)
    at Object.fireWith [as resolveWith] (jquery-latest.min.js:2:29039)
    at l (jquery-latest.min.js:2:79817)
    at XMLHttpRequest.<anonymous> (jquery-latest.min.js:2:82271)
jquery-latest.min.js:2 jQuery.Deferred exception: Cannot read properties of undefined (reading 'indexOf') TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Object.<anonymous> (http://k162/plugin.php?plugin=fpp-WledEffects&page=wledeffects.js&nopage=1:151:71)
    at Function.each (http://k162/js/jquery-latest.min.js:2:2976)
    at http://k162/plugin.php?plugin=fpp-WledEffects&page=wledeffects.js&nopage=1:150:27
    at e (http://k162/js/jquery-latest.min.js:2:30005)
    at t (http://k162/js/jquery-latest.min.js:2:30307) undefined
S.Deferred.exceptionHook @ jquery-latest.min.js:2
DevTools failed to load source map: Could not load content for http://k162/js/jquery.jgrowl.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://k162/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by TechTurtleTube** [comment]
![Screenshot 2022-07-26 2321592](https://user-images.githubusercontent.com/54298835/181153854-70dfd3cd-23c8-4977
![Screenshot 2022-07-26 232159](https://user-images.githubusercontent.com/54298835/181153857-3da627fa-6963-4bef-a6e5-8aaf5f0c1a08.png)
-8222-44b8479f2b0e.png)

**Comment by ravenridgelights-turtle** [comment]
![Screenshot 2022-07-26 2321592](https://user-images.githubusercontent.com/54298835/181153893-e2a8b28d-b24d-401f-84f1-8a3cd04092b6.png)

**Comment by ravenridgelights-turtle** [comment]
![Screenshot 2022-07-26 232159](https://user-images.githubusercontent.com/54298835/181153919-dbfbe798-275c-4980-a905-2c96c98b3335.png)

**Comment by ravenridgelights-turtle** [comment]
also fails to load on BRAVE browser

**Comment by cbennett6008** [comment]
I'm on FPP6 (with no proxy) and seeing the same symptom where there are no models listed, and colors buttons do not function.

**Comment by adamcoulombe** [comment]
i think the issue is that there is no plugin config file present when the plugin is newly installed.

I was seeing the same blank page on my end, but my console errors were actually a little different.

I've pushed a code fix, for it, maybe someone else can confirm whether it is working. (You will need to uninstall the plugin then reinstall it)

**Comment by cbennett6008** [comment]
That looks like we're closer.   After uninstalling and reinstalling i had the same problem, so I dug into the code you committed today, to find where to look for the config file, and see what was in there.
It only contained
```
{
    "models": []
}
```
I couldn't tell if the timestamp on the file was before or after the fresh install to be fair, but you have code to default falues if no config exists,  So I deleted the config file and refreshed the page.  I now have models and colors enumerated.

I have a new problem from there that is probably best if I start a new issue for, for sake of order.
Edit:  I went back and looked, plugin install timestamp was 20:17 and the config file timestamp on the broken file was 20:23

**Comment by jeepinjason** [comment]
I just upgraded to FPP 6.0 and uninstalled and reinstalled the plugin and it's still not working.

**Comment by jeepinjason** [comment]
Fresh FPP 6.0 image on a new pi, and the WLED effects looks like it's working better.  Color chooser is working.  Not sure if model list is working, because I haven't set up models yet.  Not sure what this information does to help, but I figured it cannot hurt.

**Comment by adamcoulombe** [comment]
> Fresh FPP 6.0 image on a new pi, and the WLED effects looks like it's working better. Color chooser is working. Not sure if model list is working, because I haven't set up models yet. Not sure what this information does to help, but I figured it cannot hurt.

Any changes in your console log?

BTW... I believe you do need to have models for it to work
